apiVersion: v1
kind: Secret
metadata:
  name: azure-devops-secrets
type: Opaque
data:
  AZURE_DEVOPS_API_URL: BASE64_ENCODED_API_URL # Replace with: echo -n 'your_api_url' | base64
  AZURE_DEVOPS_PAT: BASE64_ENCODED_PAT # Replace with: echo -n 'your_pat' | base64
